"""create_morphologies_table

Revision ID: 340e111cf754
Revises: dc67ded4d00b
Create Date: 2026-07-29 14:38:28.457688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340e111cf754'
down_revision: Union[str, Sequence[str], None] = 'dc67ded4d00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('normal_forms_percent', sa.Float(), nullable=False),
    sa.Column('head_defects_percent', sa.Float(), nullable=False),
    sa.Column('neck_midpiece_defects_percent', sa.Float(), nullable=False),
    sa.Column('tail_defects_percent', sa.Float(), nullable=False),
    sa.Column('excess_residual_cytoplasm_percent', sa.Float(), nullable=False),
    sa.Column('sperm_evaluated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_index(op.f('ix_morphologies_id'), 'morphologies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_morphologies_id'), table_name='morphologies')
    op.drop_table('morphologies')
    # ### end Alembic commands ###
