"""add patient address

Revision ID: 35f0cf7f90b9
Revises: 7aa90b6239e6
Create Date: 2026-08-03 15:44:37.011638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f0cf7f90b9'
down_revision: Union[str, Sequence[str], None] = '7aa90b6239e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dfis', 'non_fragmented_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'fragmented_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'large_halo_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'medium_halo_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'small_halo_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'no_halo_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dfis', 'degraded_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('patients', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address')
    op.alter_column('dfis', 'degraded_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'no_halo_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'small_halo_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'medium_halo_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'large_halo_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'fragmented_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dfis', 'non_fragmented_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
