"""update morphology schema

Revision ID: 6fd845b9947c
Revises: 8221d302430a
Create Date: 2026-08-02 19:35:21.756595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd845b9947c'
down_revision: Union[str, Sequence[str], None] = '8221d302430a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morphologies', sa.Column('midpiece_defects_percent', sa.Float(), nullable=False))
    op.add_column('morphologies', sa.Column('pin_heads_percent', sa.Float(), nullable=False))
    op.add_column('morphologies', sa.Column('live_sperm_percent', sa.Float(), nullable=False))
    op.add_column('morphologies', sa.Column('dead_sperm_percent', sa.Float(), nullable=False))
    op.add_column('morphologies', sa.Column('fructose', sa.String(length=20), nullable=False))
    op.add_column('morphologies', sa.Column('aggregation_agglutination', sa.String(length=20), nullable=False))
    op.add_column('morphologies', sa.Column('comments', sa.Text(), nullable=True))
    op.drop_column('morphologies', 'sperm_evaluated')
    op.drop_column('morphologies', 'excess_residual_cytoplasm_percent')
    op.drop_column('morphologies', 'neck_midpiece_defects_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morphologies', sa.Column('neck_midpiece_defects_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('morphologies', sa.Column('excess_residual_cytoplasm_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('morphologies', sa.Column('sperm_evaluated', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('morphologies', 'comments')
    op.drop_column('morphologies', 'aggregation_agglutination')
    op.drop_column('morphologies', 'fructose')
    op.drop_column('morphologies', 'dead_sperm_percent')
    op.drop_column('morphologies', 'live_sperm_percent')
    op.drop_column('morphologies', 'pin_heads_percent')
    op.drop_column('morphologies', 'midpiece_defects_percent')
    # ### end Alembic commands ###
