"""convert dfi percentages to counts

Revision ID: 7aa90b6239e6
Revises: f747377838c3
Create Date: 2026-08-03 12:39:45.702790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa90b6239e6'
down_revision: Union[str, Sequence[str], None] = 'f747377838c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfis', sa.Column('non_fragmented_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('fragmented_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('large_halo_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('medium_halo_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('small_halo_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('no_halo_count', sa.Integer(), nullable=True))
    op.add_column('dfis', sa.Column('degraded_count', sa.Integer(), nullable=True))
    op.drop_column('dfis', 'fragmented_percent')
    op.drop_column('dfis', 'medium_halo_percent')
    op.drop_column('dfis', 'degraded_percent')
    op.drop_column('dfis', 'large_halo_percent')
    op.drop_column('dfis', 'non_fragmented_percent')
    op.drop_column('dfis', 'no_halo_percent')
    op.drop_column('dfis', 'small_halo_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfis', sa.Column('small_halo_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('no_halo_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('non_fragmented_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('large_halo_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('degraded_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('medium_halo_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('fragmented_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('dfis', 'degraded_count')
    op.drop_column('dfis', 'no_halo_count')
    op.drop_column('dfis', 'small_halo_count')
    op.drop_column('dfis', 'medium_halo_count')
    op.drop_column('dfis', 'large_halo_count')
    op.drop_column('dfis', 'fragmented_count')
    op.drop_column('dfis', 'non_fragmented_count')
    # ### end Alembic commands ###
