"""redesign semen analyses

Revision ID: 8221d302430a
Revises: a9e9cd686b87
Create Date: 2026-07-31 15:12:19.687102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8221d302430a'
down_revision: Union[str, Sequence[str], None] = 'a9e9cd686b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semen_analyses', sa.Column('criteria', sa.String(length=30), nullable=False))
    op.add_column('semen_analyses', sa.Column('sperm_concentration_million_ml', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('wbc_concentration_million_ml', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('pus_cells', sa.String(length=20), nullable=False))
    op.add_column('semen_analyses', sa.Column('debris', sa.String(length=20), nullable=False))
    op.add_column('semen_analyses', sa.Column('agglutination', sa.String(length=20), nullable=False))
    op.add_column('semen_analyses', sa.Column('rapid_progressive_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('slow_progressive_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('non_progressive_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('immotile_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('morphology_normal_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('morphology_abnormal_percent', sa.Float(), nullable=False))
    op.add_column('semen_analyses', sa.Column('comments', sa.Text(), nullable=True))
    op.alter_column('semen_analyses', 'appearance',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('semen_analyses', 'viscosity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_column('semen_analyses', 'morphology_percent')
    op.drop_column('semen_analyses', 'concentration_million_ml')
    op.drop_column('semen_analyses', 'wbc_million_ml')
    op.drop_column('semen_analyses', 'vitality_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semen_analyses', sa.Column('vitality_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('semen_analyses', sa.Column('wbc_million_ml', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('semen_analyses', sa.Column('concentration_million_ml', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('semen_analyses', sa.Column('morphology_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('semen_analyses', 'viscosity',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('semen_analyses', 'appearance',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('semen_analyses', 'comments')
    op.drop_column('semen_analyses', 'morphology_abnormal_percent')
    op.drop_column('semen_analyses', 'morphology_normal_percent')
    op.drop_column('semen_analyses', 'immotile_percent')
    op.drop_column('semen_analyses', 'non_progressive_percent')
    op.drop_column('semen_analyses', 'slow_progressive_percent')
    op.drop_column('semen_analyses', 'rapid_progressive_percent')
    op.drop_column('semen_analyses', 'agglutination')
    op.drop_column('semen_analyses', 'debris')
    op.drop_column('semen_analyses', 'pus_cells')
    op.drop_column('semen_analyses', 'wbc_concentration_million_ml')
    op.drop_column('semen_analyses', 'sperm_concentration_million_ml')
    op.drop_column('semen_analyses', 'criteria')
    # ### end Alembic commands ###
