"""add collection fields to samples

Revision ID: a9e9cd686b87
Revises: 1c4a9c68db13
Create Date: 2026-07-31 12:34:13.960290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e9cd686b87'
down_revision: Union[str, Sequence[str], None] = '1c4a9c68db13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('collection_method', sa.String(length=50), nullable=True))
    op.add_column('samples', sa.Column('collection_place', sa.String(length=50), nullable=True))
    op.add_column('samples', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'remarks')
    op.drop_column('samples', 'collection_place')
    op.drop_column('samples', 'collection_method')
    # ### end Alembic commands ###
