"""create_semen_analyses_table

Revision ID: dc67ded4d00b
Revises: d9099fb825f0
Create Date: 2026-07-28 23:26:45.062859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc67ded4d00b'
down_revision: Union[str, Sequence[str], None] = 'd9099fb825f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semen_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('concentration_million_ml', sa.Float(), nullable=False),
    sa.Column('total_motility_percent', sa.Float(), nullable=False),
    sa.Column('progressive_motility_percent', sa.Float(), nullable=False),
    sa.Column('morphology_percent', sa.Float(), nullable=False),
    sa.Column('vitality_percent', sa.Float(), nullable=False),
    sa.Column('wbc_million_ml', sa.Float(), nullable=False),
    sa.Column('liquefaction_minutes', sa.Integer(), nullable=False),
    sa.Column('viscosity', sa.String(length=50), nullable=False),
    sa.Column('appearance', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_index(op.f('ix_semen_analyses_id'), 'semen_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semen_analyses_id'), table_name='semen_analyses')
    op.drop_table('semen_analyses')
    # ### end Alembic commands ###
