"""make patient_code nullable

Revision ID: e966946e9533
Revises: 3256bb410f9e
Create Date: 2026-07-28 16:49:48.543614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e966946e9533'
down_revision: Union[str, Sequence[str], None] = '3256bb410f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'patient_code',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'patient_code',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###
