"""update dfi schema

Revision ID: f747377838c3
Revises: 6fd845b9947c
Create Date: 2026-08-03 11:23:01.397123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f747377838c3'
down_revision: Union[str, Sequence[str], None] = '6fd845b9947c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfis', sa.Column('volume_ml', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('liquefaction_minutes', sa.Integer(), nullable=False))
    op.add_column('dfis', sa.Column('viscosity', sa.String(length=30), nullable=False))
    op.add_column('dfis', sa.Column('ph', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('sperm_concentration_raw', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('non_fragmented_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('fragmented_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('large_halo_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('medium_halo_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('small_halo_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('no_halo_percent', sa.Float(), nullable=False))
    op.add_column('dfis', sa.Column('degraded_percent', sa.Float(), nullable=False))
    op.drop_column('dfis', 'dfi_percent')
    op.drop_column('dfis', 'method')
    op.drop_column('dfis', 'hds_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfis', sa.Column('hds_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dfis', sa.Column('dfi_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('dfis', 'degraded_percent')
    op.drop_column('dfis', 'no_halo_percent')
    op.drop_column('dfis', 'small_halo_percent')
    op.drop_column('dfis', 'medium_halo_percent')
    op.drop_column('dfis', 'large_halo_percent')
    op.drop_column('dfis', 'fragmented_percent')
    op.drop_column('dfis', 'non_fragmented_percent')
    op.drop_column('dfis', 'sperm_concentration_raw')
    op.drop_column('dfis', 'ph')
    op.drop_column('dfis', 'viscosity')
    op.drop_column('dfis', 'liquefaction_minutes')
    op.drop_column('dfis', 'volume_ml')
    # ### end Alembic commands ###
